/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreateEditRecepient = CreateEditRecepient1 & CreateEditRecepient2;
export type CreateEditRecepient2 =
  | {
      key_type: "EMAIL";
      key_value: string;
      [k: string]: unknown;
    }
  | {
      key_type: "CPF";
      key_value: string;
      [k: string]: unknown;
    }
  | {
      key_type: "CNPJ";
      key_value: string;
      [k: string]: unknown;
    }
  | {
      key_type: "TELEFONE";
      key_value: string;
      [k: string]: unknown;
    }
  | {
      key_type: "CHAVE_ALEATORIA";
      key_value: string;
      [k: string]: unknown;
    };

export interface CreateEditRecepient1 {
  name: string;
  email?: string;
  cpf_cnpj: string;
  [k: string]: unknown;
}
