/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Receiver {
  id?: string;
  name: string;
  cpf_cnpj?: string;
  key_type: string;
  key_value: number;
  bank: string;
  agency: string;
  account: string;
  status: keyof typeof Status;
  [k: string]: unknown;
}

export enum Status {
  VALIDADO = "VALIDADO",
  RASCUNHO = "RASCUNHO"
}
