// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.0
// source: recipients.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyTypes int32

const (
	KeyTypes_EMAIL           KeyTypes = 0
	KeyTypes_CPF             KeyTypes = 2
	KeyTypes_CNPJ            KeyTypes = 3
	KeyTypes_TELEFONE        KeyTypes = 4
	KeyTypes_CHAVE_ALEATORIA KeyTypes = 5
)

// Enum value maps for KeyTypes.
var (
	KeyTypes_name = map[int32]string{
		0: "EMAIL",
		2: "CPF",
		3: "CNPJ",
		4: "TELEFONE",
		5: "CHAVE_ALEATORIA",
	}
	KeyTypes_value = map[string]int32{
		"EMAIL":           0,
		"CPF":             2,
		"CNPJ":            3,
		"TELEFONE":        4,
		"CHAVE_ALEATORIA": 5,
	}
)

func (x KeyTypes) Enum() *KeyTypes {
	p := new(KeyTypes)
	*p = x
	return p
}

func (x KeyTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_recipients_proto_enumTypes[0].Descriptor()
}

func (KeyTypes) Type() protoreflect.EnumType {
	return &file_recipients_proto_enumTypes[0]
}

func (x KeyTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyTypes.Descriptor instead.
func (KeyTypes) EnumDescriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_VALIDADO Status = 0
	Status_RASCUNHO Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "VALIDADO",
		1: "RASCUNHO",
	}
	Status_value = map[string]int32{
		"VALIDADO": 0,
		"RASCUNHO": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_recipients_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_recipients_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{1}
}

type ListRecipientsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemsPerPage int32  `protobuf:"varint,1,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	Status       string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	KeyType      string `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	KeyValue     string `protobuf:"bytes,4,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	Name         string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListRecipientsRequest) Reset() {
	*x = ListRecipientsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipientsRequest) ProtoMessage() {}

func (x *ListRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ListRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{0}
}

func (x *ListRecipientsRequest) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

func (x *ListRecipientsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRecipientsRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *ListRecipientsRequest) GetKeyValue() string {
	if x != nil {
		return x.KeyValue
	}
	return ""
}

func (x *ListRecipientsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRecipientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipient *Recipient `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *CreateRecipientRequest) Reset() {
	*x = CreateRecipientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipientRequest) ProtoMessage() {}

func (x *CreateRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipientRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipientRequest) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRecipientRequest) GetRecipient() *Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type EditRecipientequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Recipient *Recipient `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
}

func (x *EditRecipientequest) Reset() {
	*x = EditRecipientequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditRecipientequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRecipientequest) ProtoMessage() {}

func (x *EditRecipientequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRecipientequest.ProtoReflect.Descriptor instead.
func (*EditRecipientequest) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{2}
}

func (x *EditRecipientequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditRecipientequest) GetRecipient() *Recipient {
	if x != nil {
		return x.Recipient
	}
	return nil
}

type DeleteRecipientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteRecipientRequest) Reset() {
	*x = DeleteRecipientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRecipientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipientRequest) ProtoMessage() {}

func (x *DeleteRecipientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipientRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecipientRequest) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRecipientRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BulkDeleteRecipientsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *BulkDeleteRecipientsRequest) Reset() {
	*x = BulkDeleteRecipientsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkDeleteRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeleteRecipientsRequest) ProtoMessage() {}

func (x *BulkDeleteRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeleteRecipientsRequest.ProtoReflect.Descriptor instead.
func (*BulkDeleteRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{4}
}

func (x *BulkDeleteRecipientsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ListRecipientsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data  []*Recipient `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListRecipientsReply) Reset() {
	*x = ListRecipientsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipientsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipientsReply) ProtoMessage() {}

func (x *ListRecipientsReply) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipientsReply.ProtoReflect.Descriptor instead.
func (*ListRecipientsReply) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{5}
}

func (x *ListRecipientsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRecipientsReply) GetData() []*Recipient {
	if x != nil {
		return x.Data
	}
	return nil
}

type BulkDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *BulkDeleteResponse) Reset() {
	*x = BulkDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkDeleteResponse) ProtoMessage() {}

func (x *BulkDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkDeleteResponse.ProtoReflect.Descriptor instead.
func (*BulkDeleteResponse) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{6}
}

func (x *BulkDeleteResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Recipient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email       string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CpfCnpj     string `protobuf:"bytes,4,opt,name=cpf_cnpj,json=cpfCnpj,proto3" json:"cpf_cnpj,omitempty"`
	KeyType     string `protobuf:"bytes,5,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	Status      string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	KeyValue    string `protobuf:"bytes,7,opt,name=key_value,json=keyValue,proto3" json:"key_value,omitempty"`
	Bank        string `protobuf:"bytes,8,opt,name=bank,proto3" json:"bank,omitempty"`
	Account     string `protobuf:"bytes,9,opt,name=account,proto3" json:"account,omitempty"`
	AccountType string `protobuf:"bytes,10,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Agency      string `protobuf:"bytes,11,opt,name=agency,proto3" json:"agency,omitempty"`
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recipients_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_recipients_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_recipients_proto_rawDescGZIP(), []int{7}
}

func (x *Recipient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetCpfCnpj() string {
	if x != nil {
		return x.CpfCnpj
	}
	return ""
}

func (x *Recipient) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *Recipient) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Recipient) GetKeyValue() string {
	if x != nil {
		return x.KeyValue
	}
	return ""
}

func (x *Recipient) GetBank() string {
	if x != nil {
		return x.Bank
	}
	return ""
}

func (x *Recipient) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Recipient) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Recipient) GetAgency() string {
	if x != nil {
		return x.Agency
	}
	return ""
}

var File_recipients_proto protoreflect.FileDescriptor

var file_recipients_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa1, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a,
	0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x13, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28,
	0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x1b, 0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x2a, 0x0a, 0x12, 0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x99, 0x02, 0x0a,
	0x09, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x66, 0x5f, 0x63, 0x6e, 0x70, 0x6a,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x70, 0x66, 0x43, 0x6e, 0x70, 0x6a, 0x12,
	0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x61, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62,
	0x61, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x2a, 0x4b, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x43, 0x50, 0x46, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x4e, 0x50, 0x4a,
	0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x45, 0x4c, 0x45, 0x46, 0x4f, 0x4e, 0x45, 0x10, 0x04,
	0x12, 0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x4c, 0x45, 0x41, 0x54, 0x4f,
	0x52, 0x49, 0x41, 0x10, 0x05, 0x2a, 0x24, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0c, 0x0a, 0x08, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x41, 0x44, 0x4f, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x41, 0x53, 0x43, 0x55, 0x4e, 0x48, 0x4f, 0x10, 0x01, 0x32, 0xc9, 0x02, 0x0a, 0x0a,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x40, 0x0a, 0x0e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x69, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0d, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x2e,
	0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x45, 0x0a, 0x14, 0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2f, 0x6c, 0x75, 0x63, 0x61, 0x73, 0x70, 0x65, 0x72, 0x65, 0x2f, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x65, 0x72, 0x61, 0x5f, 0x41, 0x50, 0x49, 0x5f, 0x54, 0x65, 0x73, 0x74, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recipients_proto_rawDescOnce sync.Once
	file_recipients_proto_rawDescData = file_recipients_proto_rawDesc
)

func file_recipients_proto_rawDescGZIP() []byte {
	file_recipients_proto_rawDescOnce.Do(func() {
		file_recipients_proto_rawDescData = protoimpl.X.CompressGZIP(file_recipients_proto_rawDescData)
	})
	return file_recipients_proto_rawDescData
}

var file_recipients_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_recipients_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_recipients_proto_goTypes = []interface{}{
	(KeyTypes)(0),                       // 0: KeyTypes
	(Status)(0),                         // 1: Status
	(*ListRecipientsRequest)(nil),       // 2: ListRecipientsRequest
	(*CreateRecipientRequest)(nil),      // 3: CreateRecipientRequest
	(*EditRecipientequest)(nil),         // 4: EditRecipientequest
	(*DeleteRecipientRequest)(nil),      // 5: DeleteRecipientRequest
	(*BulkDeleteRecipientsRequest)(nil), // 6: BulkDeleteRecipientsRequest
	(*ListRecipientsReply)(nil),         // 7: ListRecipientsReply
	(*BulkDeleteResponse)(nil),          // 8: BulkDeleteResponse
	(*Recipient)(nil),                   // 9: Recipient
	(*emptypb.Empty)(nil),               // 10: google.protobuf.Empty
}
var file_recipients_proto_depIdxs = []int32{
	9,  // 0: CreateRecipientRequest.recipient:type_name -> Recipient
	9,  // 1: EditRecipientequest.recipient:type_name -> Recipient
	9,  // 2: ListRecipientsReply.data:type_name -> Recipient
	2,  // 3: Recipients.ListRecipients:input_type -> ListRecipientsRequest
	3,  // 4: Recipients.CreateRicipient:input_type -> CreateRecipientRequest
	4,  // 5: Recipients.EditRecipient:input_type -> EditRecipientequest
	5,  // 6: Recipients.DelteRecipient:input_type -> DeleteRecipientRequest
	2,  // 7: Recipients.BulkDeleteRecipients:input_type -> ListRecipientsRequest
	7,  // 8: Recipients.ListRecipients:output_type -> ListRecipientsReply
	9,  // 9: Recipients.CreateRicipient:output_type -> Recipient
	9,  // 10: Recipients.EditRecipient:output_type -> Recipient
	10, // 11: Recipients.DelteRecipient:output_type -> google.protobuf.Empty
	8,  // 12: Recipients.BulkDeleteRecipients:output_type -> BulkDeleteResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_recipients_proto_init() }
func file_recipients_proto_init() {
	if File_recipients_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recipients_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipientsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditRecipientequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRecipientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkDeleteRecipientsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipientsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recipients_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Recipient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recipients_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recipients_proto_goTypes,
		DependencyIndexes: file_recipients_proto_depIdxs,
		EnumInfos:         file_recipients_proto_enumTypes,
		MessageInfos:      file_recipients_proto_msgTypes,
	}.Build()
	File_recipients_proto = out.File
	file_recipients_proto_rawDesc = nil
	file_recipients_proto_goTypes = nil
	file_recipients_proto_depIdxs = nil
}
